# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 1
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.cache/wt [current_project]
set_property parent.project_path /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/sage/Downloads/ds_image.coe
add_files /home/sage/Downloads/ds_color_map_red.coe
add_files /home/sage/Downloads/ds_color_map_green.coe
add_files /home/sage/Downloads/ds_color_map_blue.coe
add_files /home/sage/Downloads/synth_image.coe
add_files /home/sage/Space-Synth/SpaceSynth_All/synth_image.coe
add_files /home/sage/Space-Synth/SpaceSynth_All/ds_color_map_red.coe
add_files /home/sage/Space-Synth/SpaceSynth_All/ds_color_map_green.coe
add_files /home/sage/Space-Synth/SpaceSynth_All/ds_color_map_blue.coe
read_verilog -library xil_defaultlib -sv {
  /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/new/amplitude_control.sv
  /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/new/camera_read.sv
  /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/new/camera_to_mask.sv
  /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/new/center_finder.sv
  /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/new/filter.sv
  /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/new/filter_coeffs.sv
  /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/new/image_ROM_synth.sv
  /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/new/mixer.sv
  /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/new/oscillator.sv
  /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/new/pwm.sv
  /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/new/rgb_to_hsv.sv
  /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/new/synthesizer.sv
  /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/new/xvga.sv
  /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/new/top_level.sv
}
read_ip -quiet /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/ip/green_mask_bram/green_mask_bram.xci
set_property used_in_implementation false [get_files -all /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/ip/green_mask_bram/green_mask_bram_ooc.xdc]

read_ip -quiet /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/ip/blue_mask_bram/blue_mask_bram.xci
set_property used_in_implementation false [get_files -all /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/ip/blue_mask_bram/blue_mask_bram_ooc.xdc]

read_ip -quiet /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/ip/average_divider/average_divider.xci
set_property used_in_implementation false [get_files -all /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/ip/average_divider/average_divider_ooc.xdc]

read_ip -quiet /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/ip/red_mask_bram/red_mask_bram.xci
set_property used_in_implementation false [get_files -all /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/ip/red_mask_bram/red_mask_bram_ooc.xdc]

read_ip -quiet /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/ip/image_bram/image_bram.xci
set_property used_in_implementation false [get_files -all /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/ip/image_bram/image_bram_ooc.xdc]

read_ip -quiet /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/ip/div_gen_0/div_gen_0.xci
set_property used_in_implementation false [get_files -all /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/ip/div_gen_0/div_gen_0_ooc.xdc]

read_ip -quiet /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0_ooc.xdc]

read_ip -quiet /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/ip/image_rom_1/image_rom_1.xci
set_property used_in_implementation false [get_files -all /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/ip/image_rom_1/image_rom_1_ooc.xdc]

read_ip -quiet /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/ip/red_coe/red_coe.xci
set_property used_in_implementation false [get_files -all /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/ip/red_coe/red_coe_ooc.xdc]

read_ip -quiet /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/ip/green_coe/green_coe.xci
set_property used_in_implementation false [get_files -all /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/ip/green_coe/green_coe_ooc.xdc]

read_ip -quiet /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/ip/blue_coe/blue_coe.xci
set_property used_in_implementation false [get_files -all /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/ip/blue_coe/blue_coe_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/constrs_1/imports/Lab5a/nexys4ddr_audio.xdc
set_property used_in_implementation false [get_files /home/sage/Space-Synth/SpaceSynth_All/SpaceSynth_All.srcs/constrs_1/imports/Lab5a/nexys4ddr_audio.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_level -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_level.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_level_utilization_synth.rpt -pb top_level_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
