# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Praj/Documents/2020 Fall/6.111/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/ip/image_bram/image_bram.xci
# IP: The module: 'image_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Praj/Documents/2020 Fall/6.111/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/ip/image_bram/image_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_bram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Praj/Documents/2020 Fall/6.111/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/ip/image_bram/image_bram.xci
# IP: The module: 'image_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Praj/Documents/2020 Fall/6.111/SpaceSynth_All/SpaceSynth_All.srcs/sources_1/ip/image_bram/image_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_bram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
